//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShiftEntities : DbContext
    {
        public ShiftEntities()
            : base("name=ShiftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_Car> tb_Car { get; set; }
        public virtual DbSet<tb_Color> tb_Color { get; set; }
        public virtual DbSet<tb_Contract> tb_Contract { get; set; }
        public virtual DbSet<tb_DriveTrain> tb_DriveTrain { get; set; }
        public virtual DbSet<tb_Features> tb_Features { get; set; }
        public virtual DbSet<tb_FuelStyle> tb_FuelStyle { get; set; }
        public virtual DbSet<tb_Make> tb_Make { get; set; }
        public virtual DbSet<tb_Permision> tb_Permision { get; set; }
        public virtual DbSet<tb_RepairList> tb_RepairList { get; set; }
        public virtual DbSet<tb_Shift> tb_Shift { get; set; }
        public virtual DbSet<tb_Status> tb_Status { get; set; }
        public virtual DbSet<tb_Style> tb_Style { get; set; }
        public virtual DbSet<tb_Timetable> tb_Timetable { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
    }
}
