//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Car()
        {
            this.tb_Contract = new HashSet<tb_Contract>();
        }
    
        public long IDCar { get; set; }
        public string CarName { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> RentPrice { get; set; }
        public Nullable<int> KmRun { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> FeaturesID { get; set; }
        public Nullable<int> StyleID { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<int> FuelID { get; set; }
        public Nullable<int> DriveTrainID { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public Nullable<int> IDStatus { get; set; }
        public Nullable<int> Accessories { get; set; }
        public Nullable<int> RepairList { get; set; }
    
        public virtual tb_Status tb_Status { get; set; }
        public virtual tb_Color tb_Color { get; set; }
        public virtual tb_DriveTrain tb_DriveTrain { get; set; }
        public virtual tb_Features tb_Features { get; set; }
        public virtual tb_FuelStyle tb_FuelStyle { get; set; }
        public virtual tb_Make tb_Make { get; set; }
        public virtual tb_RepairList tb_RepairList { get; set; }
        public virtual tb_Style tb_Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Contract> tb_Contract { get; set; }
    }
}
