//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Contract
    {
        public long IDContract { get; set; }
        public string Customer { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string CMND { get; set; }
        public string Deposit { get; set; }
        public Nullable<System.DateTime> DateRent { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public long IDUserCreate { get; set; }
        public long IDCar { get; set; }
    
        public virtual tb_Car tb_Car { get; set; }
    }
}
