//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Timetable
    {
        public long ID { get; set; }
        public long IDUser { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<long> IDShift { get; set; }
    
        public virtual tb_Shift tb_Shift { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
